# A descriptive name for your workflow
name: Build Electron App

# This section defines when the workflow will run
on:
  # Run on pushes to the 'main' branch
  push:
    branches: [ "main" ]
  # Also run on pull requests targeting the 'main' branch
  pull_request:
    branches: [ "main" ]
  # Allows you to manually trigger this workflow from the Actions tab
  workflow_dispatch:

# This section defines the jobs to be executed
jobs:
  build:
    # This strategy creates a 'matrix' to run the job on multiple operating systems
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    # The type of virtual machine to run the job on, based on the matrix
    runs-on: ${{ matrix.os }}

    # The sequence of steps to perform for the job
    steps:
    # 1. Checks out your repository's code so the job can access it
    - name: Checkout Code
      uses: actions/checkout@v4

    # ADDED THIS STEP TO INCREASE MEMORY ON LINUX RUNNERS
    - name: Set up swap space
      if: runner.os == 'Linux'
      # Corrected the typo in the 'uses' line below
      uses: pierotofy/set-swap-space-action@v2
      with:
        swap-size-gb: 10

    # 2. Sets up the correct version of Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    # 3. Installs all project dependencies
    - name: Install Dependencies
      run: npm install

    # 4. Runs the 'make' script from your package.json to build the app
    - name: Build Application
      run: npm run make

    # 5. (Optional but recommended) Uploads the finished app as an artifact
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.os }}-build
        path: out/make


