# A descriptive name for your workflow
# Forcing a new save on Sept 7, 2025
name: Build Electron App

# This section defines when the workflow will run
on:
  # Run on pushes to the 'main' branch
  push:
    branches: [ "main" ]
  # Also run on pull requests targeting the 'main' branch
  pull_request:
    branches: [ "main" ]
  # Allows you to manually trigger this workflow from the Actions tab
  workflow_dispatch:

# This section defines the jobs to be executed
jobs:
  build:
    # This strategy creates a 'matrix' to run the job on multiple operating systems
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    # The type of virtual machine to run the job on, based on the matrix
    runs-on: ${{ matrix.os }}

    # The sequence of steps to perform for the job
    steps:
    # 1. Checks out your repository's code so the job can access it
    - name: Checkout Code
      uses: actions/checkout@v4

    # ADDED THIS STEP TO INCREASE MEMORY ON LINUX RUNNERS
    - name: Set up swap space
      if: runner.os == 'Linux'
      # Corrected the typo in the 'uses' line below
      uses: pierotofy/set-swap-space-action@v2
      with:
        swap-size-gb: 10

    # 2. Sets up the correct version of Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    # 3. Installs all project dependencies
    - name: Install Dependencies
      run: npm install

    # 4. Runs the 'make' script from your package.json to build the app
    - name: Build Application
      run: npm run make

    # 5. (Optional but recommended) Uploads the finished app as an artifact
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.os }}-build
        # The path to the directory containing the build artifacts.
        path: out/make
        # What to do if no files are found. 'warn' will show a warning but not fail the workflow.
        if-no-files-found: warn

  release:
    # This job depends on the 'build' job, so it will only run after all matrix builds are successful
    needs: build
    # Only run this job when a new tag is pushed that starts with 'v' (e.g., v1.0.0, v1.2.3)
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    permissions:
      # Required to create a release and upload assets
      contents: write
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          # The path where all artifacts will be downloaded
          path: artifacts

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          # This will use the tag name for the release and automatically generate the release notes
          # from your commit messages.
          generate_release_notes: true
          # The files to upload to the release. The pattern will match all files
          # from the downloaded artifacts.
          files: |
            artifacts/**/*
