name: Release Linux (deb + optional AppImage)

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  linux:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential fakeroot dpkg-dev libarchive-tools

      - name: Install project deps
        run: npm ci

      - name: Ensure makers present
        run: |
          npm i -D @electron-forge/maker-deb
          npm i -D @electron-forge/maker-appimage

      - name: Make Linux artifacts
        run: |
          npx electron-forge make --targets=@electron-forge/maker-deb --platform=linux --arch=x64
          npx electron-forge make --targets=@electron-forge/maker-appimage --platform=linux --arch=x64

      - name: Collect artifacts
        run: |
          mkdir -p dist_upload
          find out/make/deb -type f -name "*.deb" -exec cp -v {} dist_upload/ \;
          if [ -d out/make/appimage ]; then
            find out/make/appimage -type f -name "*.AppImage" -exec cp -v {} dist_upload/ \;
          fi
          ls -la dist_upload

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          prerelease: false
          files: dist_upload/*
          generate_release_notes: true
