name: Release Linux (deb only)

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  linux:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential fakeroot dpkg-dev libarchive-tools

      - name: Install project deps
        run: npm ci

      - name: Ensure deb maker
        run: npm i -D @electron-forge/maker-deb

      - name: Make .deb (verbose)
        run: npx electron-forge make --targets=@electron-forge/maker-deb --platform=linux --arch=x64 --verbose

      - name: Collect .deb
        run: |
          mkdir -p dist_upload
          find out/make/deb -type f -name "*.deb" -exec cp -v {} dist_upload/ \;
          ls -la dist_upload

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          prerelease: false
          files: dist_upload/*
          generate_release_notes: true
